### ISSUE TITLE
Component Manager stuck after owebia shipping install

### ISSUE THREAD

**Issue by marcwales** [owebia/magento2-module-advanced-shipping#10]
Hi, 

After an successful install of owebia shipping on magento 2.1.2, i keep getting an error in "Component Manager". It keep loading without change and gives this error : 
"Couldn't get available versions for package owebia/magento2-module-advanced-setting-core" 
in the file : "/srv/data/web/vhosts/www.tubeclampstore.com/htdocs/setup/src/Magento/Setup/Model/PackagesData.php:88"
on the page : 
"setup/index.php/componentGrid/components"

The only way to regain access to the Component Manager is to uninstall Owebia shipping module... which is not the goal :) Same thing with Magento 2.1.3

Could someone help me with this ? 

Regards, 
Marc

**Comment by owebia** [comment]
Hi,

This is a known Magento 2 issue but the fix has not been released yet https://github.com/magento/magento2/issues/6718

Regards,
A.L.

**Comment by marcwales** [comment]
Hi, 

Thank you for your fast response. I see i'm not the only one, thanks for the link. 

Just one question, it says it's "closed" but i don't see the solution, is this normal ? The last post says "Fix for this issue was delivered to develop branch." what does that mean ? 

Regards, 
Marc

**Comment by owebia** [comment]
I think the code is ready to be released but has not been accepted yet for an official Magento release.

**Comment by marcwales** [comment]
ok i will wait ;)

**Comment by tlygnersjo** [comment]
Do you know if this Is fixed in latest Magento version? @owebia

**Comment by owebia** [comment]
It seems it has been fixed in Magento 2.1.5:  
https://github.com/magento/magento2/issues/6718

But I have not tested.
