### ISSUE TITLE
Error Unknown variable $item

### ISSUE THREAD

**Issue by MaxxxDev** [owebia/magento2-module-advanced-shipping#100]
Hi, I(m trying to set the shipping price PER product using your module

However, when I try to set the price using : 

'price'      => $item->product->standard_shipping,

I get the following issue : Error Unknown variable $item

Am I missing something ? Shall I call a method to access the prodcut custom attribute ?

**Comment by owebia** [comment]
Hi,

The shipping methods are per cart and not per item and a cart has several items.

You can access the cart items with `$request->all_items`:
https://owebia.com/doc/en/magento2-module-advanced-shipping#ex:sum

Best Regards,
A.L.

**Comment by MaxxxDev** [comment]
Hi !

Thank you  for your input and your help !

I'd need some more of your help if you don't mind.
I'd like to do something like :

if $item->product->standard_shipping is 0, I want the price to be 0, so free shipping,
but if the field standard_shipping is left empty, I want the method to be disabled

I tried with getAttributeText('standard_shipping') == "" but got no result

What would you recommend ?
Thanks in advance !

**Comment by owebia** [comment]
Hi,

You can probably use `$item->product->standard_shipping === ''`.
`getAttributeText` is only available for dropdown attributes.

Best Regards,
A.L.
