### ISSUE TITLE
Poids total non pris en compte dans table array_reduce ?

### ISSUE THREAD

**Issue by Perthmatth** [owebia/magento2-module-advanced-shipping#102]
Bonjour, 
J'ai un soucis avec un tableau pour retourner le prix de l'expé d'apres le poid, d'après le debug le $request->package_weight donne "2.1", mais le transporteur affiche un tarif de 7.5€ correspondant au package_weight à "0" du tableau.
Pourtant jai suivi la doc et le code me semble clean, je me suis trompé quelque part?
```
addMethod('livraison_france_conti', [
        'title'     => "Livraison France continentale",
        'enabled'   => _country('FR') && !_postcode('/^[0\\s]*9\\s*[78]/')  && _count(function ($item) { return $item->product->dpd_shipping == false; }) < 1,
        'price'     => array_reduce([ [0.0, 7.5], [1.0, 7.9], [3.0, 8.9], [5.0, 9.9], [7.0, 10.9], [11.0, 12.9], [13.0, 13.9], [15.0, 14.5], ['*', 15.0] ], function ($carry, $item) use ($request) {
                      if (isset($carry)) return $carry;
                        if (isset($item[0]) && ($request->package_weight < $item[0] || $item[0] == '*')) {
                            $carry = $item[1];
                        }
                        return $carry;
                    }),
        ]);
```
J'avoue je débute, j'étais plus à l'aise avec le Json que j'essaie de convertir suite à une migration magento 2 voici l'original ;)
```
"France continentale": {
   "shipto": "FR-(97*,98*)",
   "conditions": "  {count products where product.attribute.dpd_shipping==false}<1",
    "fees": "{table {cart.weight} in 0:7.50, 1.0:7.95, 3.0:8.95, 5.0:9.95, 7.0:10.95, 9.0:11.95, 11.0:12.90, 13.0:13.90, 15.0:14.50,29.99:15}+{table {cart.quantity} in 1:0, 3:1, 5:2,100:3}"
  }
```
Merci pour votre aide

**Comment by owebia** [comment]
Bonjour,
A première vue, la configuration semble correcte.
Le debug devrait vous aider à comprendre comment la configuration est évaluée.
Est-ce que vous pourriez envoyer le fichier log (dans var/log) via le formulaire de notre site ?

**Comment by owebia** [comment]
Closing after more than one year without additional information provided
