### ISSUE TITLE
 help on module programming

### ISSUE THREAD

**Issue by lucatiberia** [owebia/magento2-module-advanced-shipping#103]
Hello, I would like to set the shipping costs for orders that do not have products with free shipping attribute on "yes" with 0 costs and with orders that have products labeled "no" shipping costs with "array_reduce" table, the problem now arises when I have both types of products in the cart, in the sense that both free shipping and priced shipping appear. how can i do in this case to show only free shipping? here is the code i am using
`addMethod('method1', [
    'title' => "Spedizione 24H/48H",
    'enabled' => array_sum(
                        array_map(
                            function ($item) {
                                return $item->product->spedizione_gratuita == false;
                            },
                            $request->all_items
                        )),
     'price' => array_reduce([ [3.00, 7.00], [10.00, 9.00], [20.00, 12.00], [30.00, 15.00], ['*', 18.00] ], function ($carry, $item) use ($request) {
                        if (isset($carry)) return $carry;
                        if (isset($item[0]) && ($request->package_weight <= $item[0] || $item[0] == '*')) {
                            $carry = $item[1];
                        }
                        return $carry;
                    }),
]);

addMethod('method2', [
    'title' => "Spedizione (GRATUITA) 24H/48H SDA",
    'enabled' =>  array_sum(
                        array_map(
                            function ($item) {
                                return $item->product->spedizione_gratuita == true;
                            },
                            $request->all_items
                        )),
'price' => 0,

]);`

**Comment by owebia** [comment]
Hi,

You can do something like this:
```php
$freeShipping = array_sum(
    array_map(
        function ($item) {
            return $item->product->spedizione_gratuita == true;
        },
        $request->all_items
    )
);

addMethod('method1', [
    'title' => "Spedizione 24H/48H",
    'enabled' => !$freeShipping,
    'price' => array_reduce([ [3.00, 7.00], [10.00, 9.00], [20.00, 12.00], [30.00, 15.00], ['', 18.00] ], function ($carry, $item) use ($request) {
        if (isset($carry)) return $carry;
        if (isset($item[0]) && ($request->package_weight <= $item[0] || $item[0] == '')) {
            $carry = $item[1];
        }
        return $carry;
    }),
]);

addMethod('method2', [
    'title' => "Spedizione (GRATUITA) 24H/48H SDA",
    'enabled' => $freeShipping,
    'price' => 0,
]);
```

Best Regards,
A.L.

**Comment by lucatiberia** [comment]
thank you very much it is just what I was looking for, I hope it will be useful to others as well. Have a good evening
