### ISSUE TITLE
Issue with v2.4.2

### ISSUE THREAD

**Issue by digitupgr** [owebia/magento2-module-advanced-shipping#104]
Hello,

I am facing the following issue. When we enable the plug-in, display the following error as result to block all shipping methods. If disable the Advanced Shipping method all works fine.

VM164439:1 POST https://www.mydomain.com/el/rest/el/V1/guest-carts/K2tljCfKkqI1o7E0tZka7Kt1qnXK51zb/estimate-shipping-methods 500

Any idea?

Many Thanks

**Comment by owebia** [comment]
Closing after more than one year without additional information provided
