### ISSUE TITLE
Shipping Methods only for backend (actually console command)

### ISSUE THREAD

**Issue by Minirock** [owebia/magento2-module-advanced-shipping#105]
Hi there,

I'm currently migrating some orders data from a prestashop into a magento 2.

My problematic is that some old orders have shipping values which aren't valid anymore.

So I wanted to create shipping method available in the backend, adding them in the configuration; but I would like these methods not to be shown in the frontend, so as the current orders will only be created with nowadays shipping methods.

Is there a way to handle this ? 

Thanks !

**Comment by owebia** [comment]
Hi,
You can use `$app->isAdminArea()`, see https://owebia.com/doc/en/magento2-module-advanced-shipping#ref:var:global

Best Regards,
A.L.
