### ISSUE TITLE
No support for Magento v2.3.7?

### ISSUE THREAD

**Issue by craigfleming** [owebia/magento2-module-advanced-shipping#107]
Hello,

It appears that `owebia/magento2-module-advanced-shipping` has no support for v2.3.7-p2 when the server uses PHP 7.4.

v2.3.7 Magento systems should be using PHP 7.4 as per the [official system requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html). However, this then prevents installing [v2.8.0](https://github.com/owebia/magento2-module-advanced-shipping/blob/2.8.0/composer.json) of `owebia/magento2-module-advanced-shipping` that supports Magento v2.3.7.

During compilation on a v2.3.7-p2 system, the latest v2.8.10 prevents compilation:

`In ClassReader.php line 43: Class Owebia\AdvancedSettingCore\Helper\Registry does not exist`
`In ClassReader.php line 36: Class Owebia\AdvancedSettingCore\Helper\Registry does not exist`

Apart from upgrading to v2.4.3-p2, are there any versions of `owebia/magento2-module-advanced-shipping` that support v2.3.7-p2 that Adobe will be providing support to until September 2022?

**Comment by owebia** [comment]
Hi,

The module is already compatible with Magento 2.3.7

Have you installed the module using composer?

Best regards,
A.L.

**Comment by craigfleming** [comment]
Hi,

Yes, Composer was used to install the extension on the Magento system.

Can you confirm what version of Owebia_AdvancedShipping installs and compiles correctly on Magento v2.3.7 while using PHP 7.4?

I have upgraded to v2.4.3-p2 and there are no compilation issues when v2.8.10 is installed on the system.

Thanks,

Craig

**Comment by owebia** [comment]
The last version of the module is compatible with Magento 2.3.7.

Have you followed all the installations instructions given here without any error?
https://github.com/owebia/magento2-module-advanced-shipping#installation

**Comment by craigfleming** [comment]
Yes, I followed all the steps.

Turns out compilation was failing due to a custom extension that was calling `\Owebia\AdvancedSettingCore\Helper\Registry $registry,`

After fixing the custom extension, the issue is resolved.

Apologies for wasting your time.
