### ISSUE TITLE
Shipping method not showing ( when configurable variation product + simple product ) adding to cart

### ISSUE THREAD

**Issue by wajahatbashir** [owebia/magento2-module-advanced-shipping#110]
Hi,

I am getting an error, When customer have been adding Configurable variation products and other Simple products added in same cart, Then no shipping methods is showing.

If there is only configurable products OR Only simple products are in cart then shipping method is showing fine.

Kindly help me, How i can write shipping method for this issue ?

Thanks & Regards,

**Comment by owebia** [comment]
Hi,

When adding a configurable product to the cart, Magento adds two "items" in the cart:
- the parent item that contains some of the data
- the child item that contains the rest of the data (with a parent_item_id property)

Depending on what you want to achieve, you need sometimes to extract data from both items and/or exclude the parent or the child when couting items in the cart.

Here is an example that you can adapt to your own need: https://github.com/owebia/magento2-module-advanced-shipping/issues/86#issuecomment-706215587

To know where the data you need is stored, you should use the Debug option of our module.  
You will then be able to inspect the data that each item carries.

Best Regards,
A.L.
