### ISSUE TITLE
Strange Behaviour #payment window

### ISSUE THREAD

**Issue by MLisiecki** [owebia/magento2-module-advanced-shipping#118]
Hi,
I have strange behavior in the checkout/#shipping window. I don't know why, but it doesn't update my shipping price correctly in the window on the right (summary). When I go to the checkout/#payment sub-page, the correct price pops up, but when I go back to the #shipping sub-page - the price change in the summary stops working again. The error console does not indicate any problem related to js. Can you give me a hint as to whether this could be related to the performance of your module and if you think not - could you be so kind as to suggest where I should start looking for the cause.

Link to a video illustrating the problem.
Video: https://drive.google.com/file/d/1trlaGtYqPZNOEShjkUA_Iy64et-PHdfu/view?usp=drive_link

Regards and thanks in advance for your time.

**Comment by owebia** [comment]
Hi,

Our module does not touch any template of the checkout to avoid such problems.
Are you using a custom checkout module?
Have you overridden some behavior of the checkout page?

Best Regards,
A.L.

**Comment by MLisiecki** [comment]
Hi A.L,

I don't know - I just have been hired to create shipping rules. I will pass Your information "Our module does not touch any template of the checkout to avoid such problems." to client, but I'm sure they will go back to me. So, I have to look for some plugins that overrides checkout.
Thank You for Your time :+1: 

Best regards
Marcin
