### ISSUE TITLE
Bitninja blocks all owebia carrier configuration updates

### ISSUE THREAD

**Issue by iphigenie** [owebia/magento2-module-advanced-shipping#119]
Hi

Bitninja seems a popular thing at the moment and many hosting companies are deploying it.
Mine added it to their server set up and since then I can't update my owebia configuration. It's php code and considered code injection.

We're trying to whitelist the magento admin admin but so far struggling to do so, simple "whitelist this rule" don't seem to do it. 

Have other customers of yours encountered this issue?

**Comment by owebia** [comment]
Hi,

This is the first report we get about such issue.
We do not know the settings of this tool.
The company providing this tool may be of better help than we are but we are interested in the solution if you get a response from them.

Best Regards,
A.L.
