### ISSUE TITLE
_setStopAtFirstMatch disable all shipping methods

### ISSUE THREAD

**Issue by kallard1** [owebia/magento2-module-advanced-shipping#120]
Hello,

I use `owebia/magento2-module-advanced-shipping:6.0.2` with the `magento2-module-adv-ship-functions-addon:6.0.1` and `owebia/magento2-module-adv-ship-unlimited-carriers-addon:6.0.1` modules, in our configuration we use the `_setStopAtFirstMatch(true)` method and, unfortunately when it is present, the delivery methods no longer appear

I've tried the simplest configuration and it doesn't work either

```php
_setStopAtFirstMatch(true)

addMethod('test', [
    'title' => 'test',
    'about' => 'test',
    'enabled' => true,
    'price' => 1.0
]);
```

I've also run tests on a blank Magento project to determine whether the problem could have come from another module or not, but the problem is still there.

I've also found that even on the first match, it will set the "enabled" option to false (tested with the basic configuration above).

Modules are enabled:

```php
'Owebia_SharedPhpConfig' => 1,
'Owebia_AdvancedShipping' => 1,
'Owebia_AdvShipFunctionsAddon' => 1,
'Owebia_AdvShipUnlimitedCarriersAddon' => 1,
'Owebia_SharedLicense' => 1,
'Owebia_CustomCarriers' => 1,
```

Thanks

**Comment by owebia** [comment]
Thanks for the report @kallard1 , we will have a look to this issue.

**Comment by owebia** [comment]
Hi @kallard1,
Could you please try with version `6.0.2` of `owebia/magento2-module-adv-ship-functions-addon`?

**Comment by kallard1** [comment]
Hello,

That's great, it's working perfectly again. Thank you, you're top notch
