### ISSUE TITLE
Shipping Methods page empty after install

### ISSUE THREAD

**Issue by avidsenWeb** [owebia/magento2-module-advanced-shipping#123]
Hi,

We have Magento 2.4.6 installed on a Debian serveur with PHP 8.1. I have installed your module with composer et followed the steps described in the readme file.
But, after that, when I connect to the admin section and go to the Shipping Methods page it is blank.

I have check th exception.log file and here is what I get :

Next Magento\Framework\Exception\LocalizedException: Invalid block type: Owebia\AdvancedShipping\Block\System\Config\Form\Field\About in /var/www/test_maisonic/vendor/magento/framework/View/Layout/Generator/Block.php:278
Stack trace:
#0 /var/www/test_maisonic/vendor/magento/framework/View/Layout/Generator/Block.php(252): Magento\Framework\View\Layout\Generator\Block->getBlockInstance()
#1 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(797): Magento\Framework\View\Layout\Generator\Block->createBlock()
#2 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(780): Magento\Framework\View\Layout->_createBlock()
#3 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(1010): Magento\Framework\View\Layout->createBlock()
#4 /var/www/test_maisonic/vendor/magento/module-config/Block/System/Config/Form.php(344): Magento\Framework\View\Layout->getBlockSingleton()
#5 /var/www/test_maisonic/vendor/magento/module-config/Block/System/Config/Form.php(316): Magento\Config\Block\System\Config\Form->_initElement()
#6 /var/www/test_maisonic/generated/code/Magento/Config/Block/System/Config/Form/Interceptor.php(32): Magento\Config\Block\System\Config\Form->initFields()
#7 /var/www/test_maisonic/vendor/magento/module-config/Block/System/Config/Form.php(256): Magento\Config\Block\System\Config\Form\Interceptor->initFields()
#8 /var/www/test_maisonic/vendor/magento/module-config/Block/System/Config/Form.php(202): Magento\Config\Block\System\Config\Form->_initGroup()
#9 /var/www/test_maisonic/generated/code/Magento/Config/Block/System/Config/Form/Interceptor.php(23): Magento\Config\Block\System\Config\Form->initForm()
#10 /var/www/test_maisonic/vendor/magento/module-config/Block/System/Config/Form.php(542): Magento\Config\Block\System\Config\Form\Interceptor->initForm()
#11 /var/www/test_maisonic/vendor/magento/framework/View/Element/AbstractBlock.php(1094): Magento\Config\Block\System\Config\Form->_beforeToHtml()
#12 /var/www/test_maisonic/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#13 /var/www/test_maisonic/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#14 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Element\AbstractBlock->toHtml()
#15 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Config\Block\System\Config\Form\Interceptor->___callParent()
#16 /var/www/test_maisonic/vendor/msp/devtools/Plugin/View/Element/AbstractBlockPlugin.php(63): Magento\Config\Block\System\Config\Form\Interceptor->Magento\Framework\Interception\{closure}()
#17 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(135): MSP\DevTools\Plugin\View\Element\AbstractBlockPlugin->aroundToHtml()
#18 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Config\Block\System\Config\Form\Interceptor->Magento\Framework\Interception\{closure}()
#19 /var/www/test_maisonic/generated/code/Magento/Config/Block/System/Config/Form/Interceptor.php(536): Magento\Config\Block\System\Config\Form\Interceptor->___callPlugins()
#20 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(578): Magento\Config\Block\System\Config\Form\Interceptor->toHtml()
#21 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#22 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#23 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->renderElement()
#24 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent()
#25 /var/www/test_maisonic/vendor/msp/devtools/Plugin/View/LayoutPlugin.php(102): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#26 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(135): MSP\DevTools\Plugin\View\LayoutPlugin->aroundRenderElement()
#27 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#28 /var/www/test_maisonic/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins()
#29 /var/www/test_maisonic/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout\Interceptor->renderElement()
#30 /var/www/test_maisonic/generated/code/Magento/Config/Block/System/Config/Edit/Interceptor.php(347): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#31 /var/www/test_maisonic/vendor/magento/module-config/view/adminhtml/templates/system/config/edit.phtml(32): Magento\Config\Block\System\Config\Edit\Interceptor->getChildHtml()
#32 /var/www/test_maisonic/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('...')
#33 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render()
#34 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent()
#35 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#36 /var/www/test_maisonic/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins()
#37 /var/www/test_maisonic/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render()
#38 /var/www/test_maisonic/generated/code/Magento/Config/Block/System/Config/Edit/Interceptor.php(185): Magento\Framework\View\Element\Template->fetchView()
#39 /var/www/test_maisonic/vendor/magento/framework/View/Element/Template.php(293): Magento\Config\Block\System\Config\Edit\Interceptor->fetchView()
#40 /var/www/test_maisonic/vendor/magento/module-backend/Block/Template.php(141): Magento\Framework\View\Element\Template->_toHtml()
#41 /var/www/test_maisonic/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Backend\Block\Template->_toHtml()
#42 /var/www/test_maisonic/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#43 /var/www/test_maisonic/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#44 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Element\AbstractBlock->toHtml()
#45 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Config\Block\System\Config\Edit\Interceptor->___callParent()
#46 /var/www/test_maisonic/vendor/msp/devtools/Plugin/View/Element/AbstractBlockPlugin.php(63): Magento\Config\Block\System\Config\Edit\Interceptor->Magento\Framework\Interception\{closure}()
#47 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(135): MSP\DevTools\Plugin\View\Element\AbstractBlockPlugin->aroundToHtml()
#48 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Config\Block\System\Config\Edit\Interceptor->Magento\Framework\Interception\{closure}()
#49 /var/www/test_maisonic/generated/code/Magento/Config/Block/System/Config/Edit/Interceptor.php(410): Magento\Config\Block\System\Config\Edit\Interceptor->___callPlugins()
#50 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(578): Magento\Config\Block\System\Config\Edit\Interceptor->toHtml()
#51 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#52 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#53 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->renderElement()
#54 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent()
#55 /var/www/test_maisonic/vendor/msp/devtools/Plugin/View/LayoutPlugin.php(102): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#56 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(135): MSP\DevTools\Plugin\View\LayoutPlugin->aroundRenderElement()
#57 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#58 /var/www/test_maisonic/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins()
#59 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#60 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#61 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#62 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->renderElement()
#63 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent()
#64 /var/www/test_maisonic/vendor/msp/devtools/Plugin/View/LayoutPlugin.php(102): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#65 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(135): MSP\DevTools\Plugin\View\LayoutPlugin->aroundRenderElement()
#66 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#67 /var/www/test_maisonic/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins()
#68 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#69 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#70 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#71 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->renderElement()
#72 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent()
#73 /var/www/test_maisonic/vendor/msp/devtools/Plugin/View/LayoutPlugin.php(102): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#74 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(135): MSP\DevTools\Plugin\View\LayoutPlugin->aroundRenderElement()
#75 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#76 /var/www/test_maisonic/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins()
#77 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#78 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#79 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#80 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->renderElement()
#81 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent()
#82 /var/www/test_maisonic/vendor/msp/devtools/Plugin/View/LayoutPlugin.php(102): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#83 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(135): MSP\DevTools\Plugin\View\LayoutPlugin->aroundRenderElement()
#84 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#85 /var/www/test_maisonic/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins()
#86 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#87 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#88 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#89 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->renderElement()
#90 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent()
#91 /var/www/test_maisonic/vendor/msp/devtools/Plugin/View/LayoutPlugin.php(102): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#92 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(135): MSP\DevTools\Plugin\View\LayoutPlugin->aroundRenderElement()
#93 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#94 /var/www/test_maisonic/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins()
#95 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#96 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#97 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#98 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->renderElement()
#99 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent()
#100 /var/www/test_maisonic/vendor/msp/devtools/Plugin/View/LayoutPlugin.php(102): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#101 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(135): MSP\DevTools\Plugin\View\LayoutPlugin->aroundRenderElement()
#102 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#103 /var/www/test_maisonic/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins()
#104 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#105 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#106 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#107 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->renderElement()
#108 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent()
#109 /var/www/test_maisonic/vendor/msp/devtools/Plugin/View/LayoutPlugin.php(102): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#110 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(135): MSP\DevTools\Plugin\View\LayoutPlugin->aroundRenderElement()
#111 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#112 /var/www/test_maisonic/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins()
#113 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#114 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#115 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#116 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->renderElement()
#117 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent()
#118 /var/www/test_maisonic/vendor/msp/devtools/Plugin/View/LayoutPlugin.php(102): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#119 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(135): MSP\DevTools\Plugin\View\LayoutPlugin->aroundRenderElement()
#120 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#121 /var/www/test_maisonic/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins()
#122 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#123 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#124 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#125 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->renderElement()
#126 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent()
#127 /var/www/test_maisonic/vendor/msp/devtools/Plugin/View/LayoutPlugin.php(102): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#128 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(135): MSP\DevTools\Plugin\View\LayoutPlugin->aroundRenderElement()
#129 /var/www/test_maisonic/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#130 /var/www/test_maisonic/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins()
#131 /var/www/test_maisonic/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout\Interceptor->renderElement()
#132 /var/www/test_maisonic/generated/code/Magento/Framework/View/Layout/Interceptor.php(50): Magento\Framework\View\Layout->getOutput()
#133 /var/www/test_maisonic/vendor/magento/framework/View/Result/Page.php(260): Magento\Framework\View\Layout\Interceptor->getOutput()
#134 /var/www/test_maisonic/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render()
#135 /var/www/test_maisonic/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(32): Magento\Framework\View\Result\Layout->renderResult()
#136 /var/www/test_maisonic/vendor/magento/framework/App/Http.php(120): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult()
#137 /var/www/test_maisonic/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#138 /var/www/test_maisonic/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#139 {main} {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): Invalid block type: Owebia\\AdvancedShipping\\Block\\System\\Config\\Form\\Field\\About at /var/www/test_maisonic/vendor/magento/framework/View/Layout/Generator/Block.php:278)
[previous exception] [object] (ReflectionException(code: -1): Class \"Owebia\\AdvancedShipping\\Block\\System\\Config\\Form\\Field\\About\" does not exist at /var/www/test_maisonic/vendor/magento/framework/Code/Reader/ClassReader.php:34)"} []

Of course, the file About is present in vendor...

I have searched in precedent issues but the users who encountered the problem didn't have installed the module with Composer which I did.

Thanks for your help.

**Comment by owebia** [comment]
Hi,

Could you please try to uninstall, then reinstall and send us by email the output of the installation commands?
contact (at) owebia (dot) com

Could you also send us your composer.json file to check if any other module could use an obsolete version of our module.
Thanks

**Comment by avidsenWeb** [comment]
Bonjour,

Puisque nous échangeons par email, il sera plus simple, je pense, de passer au français 😉

Alors, nous avons déjà plusieurs fois essayé de désinstaller et réinstaller le module, voici toutefois une capture du retour de composer :
***@***.***

Les différentes commandes de compilation s’exécutent sans erreur (pour info, le site est en mode production, nous avons aussi essayé le mode développeur sans succès) …

Il va sans dire que nous ne rencontrons aucun souci sur nos environnements de dev en local. Cependant, il s’agit d’un serveur sur lequel nous testons les modules Magento que nous souhaitons utiliser sur notre futur site donc il est possible qu’il y ait un conflit quelque part que nous ne savons pas résoudre. Par exemple, nous avons par un moment testé le module officiel de DPD (qui ne s’installe pas avec composer) pour le supprimer par la suite (il ne convient pas à nos besoins et nous avons pour projet d’acquérir le vôtre).

En pièce jointe, le composer.json

Merci de votre aide


Frédérique MOUTHE
Développeuse web

***@***.***



De : owebia ***@***.***>
Envoyé : lundi 6 mai 2024 18:11
À : owebia/magento2-module-advanced-shipping ***@***.***>
Cc : MAISONIC FRANCE - Informatique ***@***.***>; Author ***@***.***>
Objet : [EXTERNAL]Re: [owebia/magento2-module-advanced-shipping] Shipping Methods page empty after install (Issue #123)

 Ceci est un message externe. / This is an external message.


Hi,

Could you please try to uninstall, then reinstall and send us by email the output of the installation commands?
contact (at) owebia (dot) com

Could you also send us your composer.json file to check if any other module could use an obsolete version of our module.
Thanks

**Comment by owebia** [comment]
@avidsenWeb j'ai supprimé votre commentaire sur github car je ne pense pas que ce soit ce que vous souhaitiez faire. Pourriez-vous me renvoyer les éléments par email à l'adresse contact (at) owebia (dot) com sans utiliser le Reply To qui va publier sur github svp ?

**Comment by avidsenWeb** [comment]
We finally managed to resolve this problem by restarting Apache2, so it must be a misconfiguration of our web server.
