### ISSUE TITLE
Not working with magento 2.4.7-p1

### ISSUE THREAD

**Issue by magentox** [owebia/magento2-module-advanced-shipping#125]
I made an upgrade from magento 2.4.6-p5 to magento 2.4.7-p1 and owebia shipping does not display anymore. I mean when I put something in the cart I can no longer get shipping estimation on the "Estimate Shipping and Tax" page. If I disable owebia the other methods like free shipping or fixed price are displayed again. If owebia is activated, there is 0 method being displayed. No owebia, no free shipping, nothing. 

I seems that Adobe made some updates and changes on certain files related to shipping on magento 2.4.7. I will need to take a look at the release notes and changelog.

**Comment by magentox** [comment]
I am sorry for late reply.
There was no error in the logs which actually prompted me to try owebia with a brand new installed Magento 2.4.7-p1 and not an upgraded version like mine. I tried and owebia 6.0.3 worked great on a mint install. Now I think something failed on my upgrade and the problem was my install not Magento 2.4.7-p1 nor owebia.
So anyone using owebia with Magento 2.4.7-p1, no problem it works great. You might get error on a upgraded version.

**Comment by owebia** [comment]
@magentox thanks for your feedback. I'm closing this issue.
