### ISSUE TITLE
Unsupported PropertyFetch expression when using $customer->getCustomAttribute

### ISSUE THREAD

**Issue by QuentinScDS** [owebia/magento2-module-advanced-shipping#127]
Hello !
 
Magento 2.4.7
Advanced Shipping 6.0.3
PHP 8.2.20 
Test with Shared Php Config 6.0.3 and 6.1.0

As soon as I use this method ($customer->getCustomAttribute) in my configuration, I get the following error (Unsupported PropertyFetch expression).

Sample conf : 
```
// First shipping method
addMethod('method1', [
    'title' => "Standard Shipping",
    'price' => 10,
]);
// Second shipping method
addMethod('method2', [
    'title' => "Express Shipping",
    'price' => 20,
'enable' => $customer->getCustomAttribute('my_attribute_code')->value == '17'
]);
```
![image](https://github.com/user-attachments/assets/b21f891e-333b-4eb1-8589-c996dc7e0ffd)

Debug log : 
`Unsupported PropertyFetch expression`

<details>
  <summary>Stack trace</summary>

Error #0 /var/www/magento/vendor/owebia/magento2-module-shared-php-config/Model/Evaluator.php(931): 
    Owebia\SharedPhpConfig\Model\Evaluator->error()

#1 /var/www/magento/vendor/owebia/magento2-module-shared-php-config/Model/Evaluator.php(338): 
    Owebia\SharedPhpConfig\Model\Evaluator->evalNodeExprPropertyFetch()

#2 /var/www/magento/vendor/owebia/magento2-module-shared-php-config/Model/Evaluator.php(1088): 
    Owebia\SharedPhpConfig\Model\Evaluator->evalNodeExpr()

#3 /var/www/magento/vendor/owebia/magento2-module-shared-php-config/Model/Evaluator.php(614): 
    Owebia\SharedPhpConfig\Model\Evaluator->evl()

#4 /var/www/magento/vendor/owebia/magento2-module-shared-php-config/Model/Evaluator.php(264): 
    Owebia\SharedPhpConfig\Model\Evaluator->evalNodeExprBinaryOp()

#5 /var/www/magento/vendor/owebia/magento2-module-shared-php-config/Model/Evaluator.php(1088): 
    Owebia\SharedPhpConfig\Model\Evaluator->evalNodeExpr()

#6 /var/www/magento/vendor/owebia/magento2-module-shared-php-config/Model/Evaluator.php(361): 
    Owebia\SharedPhpConfig\Model\Evaluator->evl()

#7 /var/www/magento/vendor/owebia/magento2-module-shared-php-config/Model/Evaluator.php(317): 
    Owebia\SharedPhpConfig\Model\Evaluator->evalNodeExprArray()

#8 /var/www/magento/vendor/owebia/magento2-module-shared-php-config/Model/Evaluator.php(1088): 
    Owebia\SharedPhpConfig\Model\Evaluator->evalNodeExpr()

#9 /var/www/magento/vendor/owebia/magento2-module-shared-php-config/Model/Evaluator.php(1128): 
    Owebia\SharedPhpConfig\Model\Evaluator->evl()

#10 /var/www/magento/vendor/owebia/magento2-module-shared-php-config/Model/Evaluator.php(820): 
    Owebia\SharedPhpConfig\Model\Evaluator->evaluateArgs()

#11 /var/www/magento/vendor/owebia/magento2-module-shared-php-config/Model/Evaluator.php(332): 
    Owebia\SharedPhpConfig\Model\Evaluator->evalNodeExprFuncCall()

#12 /var/www/magento/vendor/owebia/magento2-module-shared-php-config/Model/Evaluator.php(1088): 
    Owebia\SharedPhpConfig\Model\Evaluator->evalNodeExpr()

#13 /var/www/magento/vendor/owebia/magento2-module-shared-php-config/Model/Evaluator.php(986): 
    Owebia\SharedPhpConfig\Model\Evaluator->evl()

#14 /var/www/magento/vendor/owebia/magento2-module-shared-php-config/Model/Evaluator.php(1086): 
    Owebia\SharedPhpConfig\Model\Evaluator->evalNodeStmt()

#15 /var/www/magento/vendor/owebia/magento2-module-shared-php-config/Model/Evaluator.php(234): 
    Owebia\SharedPhpConfig\Model\Evaluator->evl()

#16 /var/www/magento/vendor/owebia/magento2-module-shared-php-config/Model/Parser.php(127): 
    Owebia\SharedPhpConfig\Model\Evaluator->evaluate()

#17 /var/www/magento/vendor/owebia/magento2-module-shared-php-config/Model/Parser.php(104): 
    Owebia\SharedPhpConfig\Model\Parser->parseNode()

#18 /var/www/magento/vendor/owebia/magento2-module-advanced-shipping/Model/Carrier.php(226): 
    Owebia\SharedPhpConfig\Model\Parser->parse()

#19 /var/www/magento/vendor/owebia/magento2-module-advanced-shipping/Model/Carrier.php(122): 
    Owebia\AdvancedShipping\Model\Carrier->getConfig()

#20 /var/www/magento/vendor/magento/module-shipping/Model/Shipping.php(335): 
    Owebia\AdvancedShipping\Model\Carrier->collectRates()

#21 /var/www/magento/vendor/magento/module-shipping/Model/Shipping.php(244): 
    Magento\Shipping\Model\Shipping->collectCarrierRates()

#22 /var/www/magento/vendor/magento/module-quote/Model/Quote/Address.php(1090): 
    Magento\Shipping\Model\Shipping->collectRates()

#23 /var/www/magento/vendor/magento/module-quote/Model/Quote/Address.php(1017): 
    Magento\Quote\Model\Quote\Address->requestShippingRates()

#24 /var/www/magento/vendor/magento/module-quote/Model/Quote/Address/Total/Shipping.php(92): 
    Magento\Quote\Model\Quote\Address->collectShippingRates()

#25 /var/www/magento/vendor/magento/module-quote/Model/Quote/TotalsCollector.php(261): 
    Magento\Quote\Model\Quote\Address\Total\Shipping->collect()

#26 /var/www/magento/vendor/magento/module-quote/Model/ShippingMethodManagement.php(336): 
    Magento\Quote\Model\Quote\TotalsCollector->collectAddressTotals()

#27 /var/www/magento/vendor/magento/module-quote/Model/ShippingMethodManagement.php(288): 
    Magento\Quote\Model\ShippingMethodManagement->getShippingMethods()

#28 [internal function]: 
    Magento\Quote\Model\ShippingMethodManagement->estimateByAddressId()

#29 /var/www/magento/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): 
    call_user_func_array()

#30 /var/www/magento/vendor/magento/module-webapi/Controller/Rest.php(201): 
    Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process()

#31 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(58): 
    Magento\Webapi\Controller\Rest->dispatch()

#32 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): 
    Magento\Webapi\Controller\Rest\Interceptor->___callParent()

#33 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): 
    Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}()

#34 /var/www/magento/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): 
    Magento\Webapi\Controller\Rest\Interceptor->___callPlugins()

#35 /var/www/magento/vendor/magento/framework/App/Http.php(116): 
    Magento\Webapi\Controller\Rest\Interceptor->dispatch()

#36 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(58): 
    Magento\Framework\App\Http->launch()

#37 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): 
    Magento\Framework\App\Http\Interceptor->___callParent()

#38 /var/www/magento/vendor/magento/module-application-performance-monitor/Plugin/ApplicationPerformanceMonitor.php(38): 
    Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()

#39 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(135): 
    Magento\ApplicationPerformanceMonitor\Plugin\ApplicationPerformanceMonitor->aroundLaunch()

#40 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(153): 
    Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()

#41 /var/www/magento/generated/code/Magento/Framework/App/Http/Interceptor.php(23): 
    Magento\Framework\App\Http\Interceptor->___callPlugins()

#42 /var/www/magento/vendor/magento/framework/App/Bootstrap.php(264): 
    Magento\Framework\App\Http\Interceptor->launch()

#43 /var/www/magento/pub/index.php(30): 
    Magento\Framework\App\Bootstrap->run()

#44 {main}

</details>

**Comment by owebia** [comment]
Hi,

Thanks for the feedback.
We made some tests and it seems Magento returns null on a `$customer->getCustomAttribute(...)` call when 1) the custom attribute does not exist 2) the custom attribute is not set for the customer.

As a solution, you can use the following code:

```php
addMethod('method2', [
    'title' => "Express Shipping",
    'price' => 20,
    'enable' => $customer->getCustomAttribute('my_attribute_code') && $customer->getCustomAttribute('my_attribute_code')->value == '17'
]);
```

Best Regards,
A.L.

**Comment by QuentinScDS** [comment]
> Hi,
> 
> Thanks for the feedback. We made some tests and it seems Magento returns null on a `$customer->getCustomAttribute(...)` call when 1) the custom attribute does not exist 2) the custom attribute is not set for the customer.
> 
> As a solution, you can use the following code:
> 
> ```
> addMethod('method2', [
>     'title' => "Express Shipping",
>     'price' => 20,
>     'enable' => $customer->getCustomAttribute('my_attribute_code')
>         && $customer->getCustomAttribute('my_attribute_code')->value == '17'
> ]);
> ```
> 
> Best Regards, A.L.

Thank you for the answer,
Indeed, the error disappears but the condition is now evaluated as true 100% of the time, no matter what comes after the &&.

**Comment by owebia** [comment]
Did you enable the debug option and did you check how the formula is evaluated?

**Comment by QuentinScDS** [comment]
> Did you enable the debug option and did you check how the formula is evaluated?

Yes, this is the corresponding debug

> "Express Shipping"
getCustomAttribute
$customer
$customer->getCustomAttribute('spg_code')
$customer->getCustomAttribute('spg_code') && $customer->getCustomAttribute('spg_code')->value != '123'
['title' => "Express Shipping", 'price' => 10, 'enable' => $customer->getCustomAttribute('spg_code') && $customer->getCustomAttribute('spg_code')->value != '123']
addMethod('method2', ['title' => "Express Shipping", 'price' => 10, 'enable' => $customer->getCustomAttribute('spg_code') && $customer->getCustomAttribute('spg_code')->value != '123'])
addMethod('method2', ['title' => "Express Shipping", 'price' => 10, 'enable' => $customer->getCustomAttribute('spg_code') && $customer->getCustomAttribute('spg_code')->value != '123'])

**Comment by owebia** [comment]
What is the value when you get the debug of `$customer->getCustomAttribute('spg_code')`?

You can send us the debug file `var/log/owebia_advancedsettingcore.log` to the following address `contact [at] owebia [dot] com`

**Comment by QuentinScDS** [comment]
It seems to be caused by another module, I will come back to close the issue if that is indeed the case.
