### ISSUE TITLE
Custom product attributes

### ISSUE THREAD

**Issue by clivewalkden** [owebia/magento2-module-advanced-shipping#15]
Thanks for making this great plugin.

One question, how do I utilise custom product attributes to control the shipping price. I've created a boolean field product attribute which I want to check for each product in the basket. The product attribute only belongs to a single attribute set and at the moment using 
`$item->product->getAttributeText('pallet_shipping') == true` is returning true on product that don't have the attribute available to them.
Using `$item->product->pallet_shipping` is returning 0 on products in the attribute set and NULL on products not in the attribute set.

Hopefully I'm missing something really simple and this isn't an issue with the plugin.

Thanks for your time.

**Comment by owebia** [comment]
Hi,  
Do you have some informations if you activate the debug option ?  
Regards,  
A.L.

**Comment by paulpartington-cti** [comment]
I found that I needed to add the custom attribute to the quote_item. 

Create a `catalog_attributes.xml` in a module and add the below:

    <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Catalog:etc/catalog_attributes.xsd">
    <group name="quote_item">
        <attribute name="pallet_shipping"/>
    </group>
</config>

It should then be accessible.

**Comment by Gransfall** [comment]
Hello, i'm a beginner with magento 2 and i don't understand where i must create this catalog_attributes.xml :/

Can you give me the path of the folder please ?

Thanks in advance

**Comment by LiamKarlMitchell** [comment]
Could this be easier?

In normal modules I can just do ->getSomeThing() where SomeThing is really a magic getter for the some_thing attribute.

Is there something I'm missing here, I don't want the text value but the attributes value?


Could someone please explain what to do with the catalog_attributes.xml file?
Where do I put it?

**Comment by Eayshwary** [comment]
HI
can you please tell me as to how can i show shipping rates based on customer group on frontend?

**Comment by owebia** [comment]
@clivewalkden @paulpartington-cti @Gransfall @LiamKarlMitchell 

To access a custom product attribute from the configuration of Advanced Shipping, you don't need to create a `catalog_attributes.xml` file.

Just access it like this:
```
$item->product->my_custom_attribute
```

If the attribute is a dropdown attribute, you can access the value and the text like this:
```
// Get attribute value
$item->product->my_custom_attribute

// Get attribute text
$item->product->getAttributeText('my_custom_attribute')
```

If the attribute is a Yes/No attribute, you can compare the value like this:
```
// If the value selected is 'No', the stored value will be '0' (type string)  -  '0' == true will return false
// If the value selected is 'Yes', the stored value will be '1' (type string)  -  '1' == true will return true
// It the value is not defined, the stored value will be NULL  -  NULL == true will return false
$item->product->my_custom_attribute == true

// The following code will always return true as getAttributeText will always return a non empty string
// ('No', 'Yes' or their translated equivalent)
$item->product->getAttributeText('my_custom_attribute') == true
```
