### ISSUE TITLE
Blank page on frontend and 404 error on backend after installing Owebia Advanced Shipping

### ISSUE THREAD

**Issue by owebia** [owebia/magento2-module-advanced-shipping#33]
After executing `php bin/magento setup:di:compile` on a store in dev mode, we have a blank page on frontend and a 404 error on backend.

**Comment by dm8mydog** [comment]
After installation of owebia shipping the site cannot be brought back to dev mode.

php 7.1, magento 2.2.2

frontend and backend work fine while in production mode, but will go into infinite loop/infinite loading when the site is switched to developer mode. 
Things I've tried: cache flushed/cleaned and /generated folder was manually wiped before switch... and more

Now, here's the big kicker... I've tried manually disabling the module(s) via cli with module:disable and then switching to developer. But the site will continue being unresponsive and failing to fully load.

In my case, the only way to fix it was to revert to a previous VM snapshot.

Any ideas?

**Comment by owebia** [comment]
Hi @dm8mydog 
Have you runned the setup:di:compile command?

Best Regards,

**Comment by dm8mydog** [comment]
indeed

**Comment by dm8mydog** [comment]
tried it again today in a fresh install, the same behaviour occurs. So it's not caused by any other module.

**Comment by owebia** [comment]
@dm8mydog  you **SHOULD NOT** run setup:di:compile if you are in developer mode

**Comment by dm8mydog** [comment]
In the original report I mentioned I was in production mode; and that the issues begin after switching to developer mode. I think that's clear :)

In my second attempt in a fresh magento2.2.2 install, I did not run compile and I was still in developer mode, the same behaviour occurs with the endless loading, unfortunately there are no clear error messages anywhere to assist in fixing this.

I hesitate to try 2.1.7 knowing that I will soon end up in an unsupported environment.

**Comment by owebia** [comment]
Can it be related to the module configuration? Are you using $quote variable?

**Comment by dm8mydog** [comment]
I have not reached that point yet since the module causes the site to break.

**Comment by owebia** [comment]
Hmm, sorry but without any additional clue... You are the first user reporting this issue (this is not the same issue as #33).

**Comment by dm8mydog** [comment]
updated previous comment

**Comment by owebia** [comment]
Can you try these instructions on switching from production mode to developper mode?  
https://amasty.com/knowledge-base/magento-2-modes-set-developer-production-mode

**Comment by dm8mydog** [comment]
after a 3rd try and a look at your suggestion... it appears it should not matter because according to this: http://devdocs.magento.com/guides/v2.2/howdoi/php/php_clear-dirs.html
the directories are automatically cleared when switching deploy modes.

I did try doing that manually to no effect.

I'll re-state the weirdest part of this is that the issue persists even if the module is disabled via the cli. Which is very weird.

I do have a question though, the 2.0.7 version of this module appears to -almost- work on mage2.2.2, it may have broken our checkout page when I was giving it a try (other things were happening so I'm not sure)  Could you comment on what would and wouldn't work if v2.0.7 is used on mage2.2.2 ?

**Comment by owebia** [comment]
Changes since version 2.0.7:
* Allow user to refresh shipping methods on more customer address fields
* Update documentation

Changes in https://github.com/owebia/magento2-module-advanced-setting-core:
* Magento modules dependencies
* Fix issue with assigning a value to a global variable in the configuration
* Do not load customer by id when customer is not logged in
* Allow additional PHP functions: mb_strtolower, mb_strtoupper, mb_substr, preg_replace, strtolower, strtoupper and time
