### ISSUE TITLE
Infinite loop when using $quote variable on some configurations

### ISSUE THREAD

**Issue by owebia** [owebia/magento2-module-advanced-shipping#34]
On some configurations, we get an infinite loop when trying to use the $quote variable.  
This problem can't be reproduced on a new Magento installation.

The usage of $request->package_value instead of $quote->subtotal can solve the problem.

If you find the configuration leading to this infinite loop, please post it here.

**Comment by synolia-bvo** [comment]
Hello,

I think I found the issue.

The case is reproductible when there is a misconfigured "currency setup" (in Stores > Configuration > General > Currency setup): 

For example, you are on a norwegian store, so the "Default Display Currency" is "Norwegian Krone". If the "Norwegian Krone" is not selected in "Allowed currencies".

In fact, Magento, in the class \Magento\Checkout\Model\Session::getQuote tries to re-save the quote, checking at this moment some things.

I think you should not use the getQuote from the session to solve the issue.

Best,

**Comment by owebia** [comment]
Hi @synolia-bvo , thanks for your feedback, I will explore this when I will have a little time.

Best Regards,

**Comment by owebia** [comment]
@syno-bvo Do you see any difference in the last version of the module?
Quote is loaded another way.

**Comment by owebia** [comment]
Closing as it has not been reported recently
