### ISSUE TITLE
Shipping methods not changing when Owebia is the only active carrier

### ISSUE THREAD

**Issue by Axel29** [owebia/magento2-module-advanced-shipping#39]
### Preconditions
1. Magento 2.2.3
2. PHP 7.1
3. Multi website / store view instance
4. Module Aheadworks_OneStepCheckout

### Steps to reproduce
1. Install Owebia Shipping's latest version
3. Go to Store > Configuration > Sales > Shipping method
3. Enable only Owebia Shipping carrier
3. Set a shipping method for a specific dest_country_id 
![image](https://user-images.githubusercontent.com/3015249/42209878-151a40fe-7eb0-11e8-81ea-cd4abfcd66a4.png)
4. Go back to the frontend
5. Add a product to your cart
6. Go to the checkout as guest
7. Change the country to the one enabled in the carrier's configuration

### Expected result
1. The shipping methods should be reloaded

### Actual result
1. There is no AJAX call triggered
2. The shipping methods are not reloaded

The only solution I found was to enabled a system shipping method like "Free shipping" and setting a minimum amount to 9999999€ (to make sure it never shows up). Then it worked.

This solution was provided here: https://github.com/magento/magento2/issues/8240#issuecomment-343806541

I tried with the native checkout and it seems to work, so I'm guessing the problem is linked to Aheadworks Onestepcheckout.

**Comment by owebia** [comment]
Hi,

You can configure required fields for which the fees will be recalculated:  
![configuration settings stores magento admin](https://user-images.githubusercontent.com/604741/42211055-da550aa0-7eb2-11e8-9a7b-5a26ab009d7b.png)

If you already have selected the required fields, the problem is probably linked to the non standard checkout page.  
Please, contact their support team.

Best Regards,
A.L.

**Comment by Axel29** [comment]
Hi,

I've already configured the country as a required field and it still doesn't work.
I did create an issue on their help desk, I just created this one in case you already noticed the issue considering I can't reproduce this bug with other third-party extensions like Magentix_SoColissimo that works alone.

**Comment by ashvinimarwal** [comment]
I'm also facing same issue. The shipping method is not showing on the frontend.

**Comment by owebia** [comment]
Hi,

Are you using any One Step Checkout module?
Have you tried to configure required fields?

Best Regards,
A.L.

**Comment by ashvinimarwal** [comment]
I was getting following error on checkout
class 'phpparser parserfactory' not found
Finally, I have installed the extension using the composer and it's working fine.

**Comment by owebia** [comment]
Closing old issue
