### ISSUE TITLE
Extra attributes on shipping field.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [owebia/magento2-module-advanced-shipping#46]
Hi, I have extra attributes on the shipping field,
I can see these passed through the estimate shipping options AJAX request, but the values for it on the shipping address are always NULL.

Is there a way I can pass these through correctly, or pass through $_POST to the PHP code configured to run for shipping method checks?

Magento 2.2

**Comment by owebia** [comment]
Hi,

I suppose you have created a module for your custom shipping field.  
Have you added an extension_attributes.xml file?  
https://magento.stackexchange.com/questions/113447/how-to-use-extension-attributes-in-magento2

Perhaps can you assign your custom data to quote object and get it in Advanced Shipping configuration from $quote variable.

Best Regards,
A.L.

**Comment by LiamKarlMitchell** [comment]
Yes it is added in the extension_attributes.xml file, created the module to add the extra fields as well.

How would I assign it to the $quote object?

After seeing this it would appear that Magento 2 may hard code the values passed through.

https://magento.stackexchange.com/questions/219654/shipping-address-custom-attribute-value-not-getting-in-raterequest-object-in-car

The solution for them was to get it from POST, how might I pass more values as global to the script that would get the job done.

**Comment by owebia** [comment]
Hi,

You have an exemple here:
https://github.com/sohelrana09/magento2-module-delivery-date/blob/master/SR/DeliveryDate/Plugin/Checkout/Model/ShippingInformationManagement.php  
(from the previous link I posted)

Best Regards,
A.L.
