### ISSUE TITLE
Additional accepted function

### ISSUE THREAD

**Issue by tlygnersjo** [owebia/magento2-module-advanced-shipping#53]
Could you please add foreach (http://php.net/manual/en/control-structures.foreach.php) as accepted function?

In some cases you'll have to loop through rules (for example multiple rules stored in a multidimensional array).

**Comment by tlygnersjo** [comment]
I tried to add "foreach" as a allowed function in vendor/owebia/magento2-module-advanced-setting-core/Helper/Evaluator.php on at line 45.

But when i use a "foreach" in shipping rules i get:
"$shippingrules
// Result
NULL

Unsupported Foreach_ expression - Undefined variable"

Is this the wrong way to add support for "foreach" function? I'm sure the array $shippingrules is set.

**Comment by owebia** [comment]
Hi, foreach is not a function and is already supported.
You probably don't use the right syntax.
Can you post your configuration ?
A.L.

**Comment by tlygnersjo** [comment]
Hi,

Oh ok! Can i send the configuration on email or Skype?

**Comment by owebia** [comment]
You can use the contact form here:
https://en.store.owebia.com/contact

**Comment by tlygnersjo** [comment]
I've now sent the configuration to you.
