### ISSUE TITLE
Composer repository down

### ISSUE THREAD

**Issue by wclrz** [owebia/magento2-module-advanced-shipping#56]
Hello,

Since today, the composer installation of your extensions is broken due to a 404 on module license's repo.

Here is the error thrown when using composer install:

> - Updating owebia/magento2-module-license (1.0.2 => 1.0.3): Downloading (failed)    Update failed (The "https://api.github.com/repos/owebia/magento2-module-license/zipball/913f82e3a5b21c9dd7b2a71ae0a3c7e8943dab6d" file could not be downloaded (HTTP/1.1 404 Not Found))
>     Would you like to try reinstalling the package instead [yes]? no
> 
> 
>   [Composer\Downloader\TransportException]
>   The "https://api.github.com/repos/owebia/magento2-module-license/zipball/913f82e3a5b21c9dd7b2a71ae0a3c7e8943dab
>   6d" file could not be downloaded (HTTP/1.1 404 Not Found)

I can't find the repo anymore, should I remove it?

Thank you.

**Comment by owebia** [comment]
Hi,

Commercial modules have been moved to the private repository https://repo.owebia.com (your login and password are available in your Owebia Store account).

Please update your extension and look at installation instructions.

Best Regards,  
A.L.
