### ISSUE TITLE
Query a database table in the configuration code

### ISSUE THREAD

**Issue by hrmf** [owebia/magento2-module-advanced-shipping#58]
Would it be possible to add a feature that would let me query a database table in Owebia Shipping's config?

I have this list of at least 20k districts along with their respective cities and regions and a "Serviceable Area" flag. What I do with this list is the following:

1. Put this list into a single array 
2. Use array_reduce to get the "Serviceable Area" flag of a district, city, region combination based on what the customer has entered in his/her address.
3. Based on the Serviceable Area flag, compute the Shipping Rate

This currently works  (I updated Magento's core_config_data's value column to mediumtext to hold this big script) But is very unwieldy as the script bogs down the Magento site drastically. I has hoping that instead of placing the list in an array in the config script, I would use a function to query a database table from within the config script. I think **curl** functions can do this - I would just setup a web service that I will pass parameters to and then will return the flag. 

I am using Magento 2.1.12
Thank you for such a great plugin!

**Comment by owebia** [comment]
Hi,

Your request is really specific, you should create your own module if you are concerned by performance issues.

Best Regards,
A.L.
