### ISSUE TITLE
magento2-module-advanced-shipping' has been already defined 

### ISSUE THREAD

**Issue by tlf83** [owebia/magento2-module-advanced-shipping#60]
Hello,

After upgrading owebia shipping module with the install recommandation from the github, I've got only blank page on admin and front office page on my website with this error:

Autoload error

Module 'Owebia_AdvancedShipping' from '/var/www/magento/vendor/owebia/magento2-module-advanced-shipping' has been already defined in '/var/www/magento/vendor/owebia/magento2-module-advanced-shipping-setting'.

I've tried to uninstall it and reinstall it but always this error.

Any help requested, please.

**Comment by owebia** [comment]
Hi,

Can you send me your composer.json file please?

Best Regards,
A.L.

**Comment by tlf83** [comment]
Hi,

Here below:

{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.1.16",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "require": {
        "magento/product-community-edition": "2.2.2",
        "composer/composer": "@alpha",
        "magento/module-bundle-sample-data": "*",
        "magento/module-theme-sample-data": "*",
        "magento/module-catalog-sample-data": "*",
        "magento/module-cms-sample-data": "*",
        "magento/module-widget-sample-data": "*",
        "magento/module-tax-sample-data": "*",
        "magento/module-customer-sample-data": "*",
        "magento/module-catalog-rule-sample-data": "*",
        "magento/module-sales-rule-sample-data": "*",
        "magento/module-sales-sample-data": "*",
        "magento/module-grouped-product-sample-data": "*",
        "magento/module-downloadable-sample-data": "*",
        "magento/module-msrp-sample-data": "*",
        "magento/module-configurable-sample-data": "*",
        "magento/module-product-links-sample-data": "*",
        "magento/module-wishlist-sample-data": "*",
        "magento/module-review-sample-data": "*",
        "magento/module-swatches-sample-data": "*",
        "magento/sample-data-media": "*",
        "magento/module-offline-shipping-sample-data": "*",
        "acyba/module-gls": "1.0.1",
        "Imaginaerum/magento2-language-fr-fr": "*",
        "owebia/magento2-module-advanced-shipping": "^2.6.1"
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "@stable",
        "pdepend/pdepend": "2.5.0",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.8.10",
        "sebastian/phpcpd": "2.0.4"
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": [
                "app/code/"
            ]
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "alpha",
    "prefer-stable": true,
    "repositories": {
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        "owebia": {
            "type": "composer",
            "url": "https://repo.owebia.com/"
        }
    },
    "extra": {
        "magento-force": "override"
    }
}

**Comment by owebia** [comment]
Hi,

You should contact Acyba team, they must update dependency of module Advanced Shipping.
Here is their composer.json file:
```
{
  "name": "acyba/module-gls",
  "description": "Magento module for GLS Shipping. This extension is compatible with Magento v2",
  "type": "magento2-module",
  "license": "OSL-3.0",
  "version": "1.0.1",
  "authors": [
    {
      "email": "ecommerce@acyba.com",
      "name": "Acyba"
    }
  ],
  "minimum-stability": "dev",
  "require": {
    "owebia/magento2-module-advanced-setting-core": "^2.0.4",
    "owebia/magento2-module-advanced-shipping-setting": "^2.1.1"
  },
  "autoload": {
    "files": [
      "registration.php"
    ],
    "psr-4": {
      "Acyba\\GLS\\": ""
    }
  }
}
```
Best Regards,
A.L.

**Comment by iphigenie** [comment]
I am having this very same problem, but I do not have Acyba or other modules that depend on Advanced Shipping.
