### ISSUE TITLE
 The 'https://repo.owebia.com/packages.json' URL required authentication

### ISSUE THREAD

**Issue by tlf83** [owebia/magento2-module-advanced-shipping#62]
Hello,

I've got a new problem when I got o the "extension Manager"

I received this error:

Command "show" failed: [Composer\Downloader\TransportException] The 'https://repo.owebia.com/packages.json' URL required authentication. You must be using the interactive console to authenticate show [--all] [-i|--installed] [-p|--platform] [-a|--available] [-s|--self] [-N|--name-only] [-P|--path] [-t|--tree] [-l|--latest] [-o|--outdated] [-m|--minor-only] [-D|--direct] [--strict] [-f|--format FORMAT] [--] [<package>] [<version>] 

Could you help me, please?

I think it's after uninstalling the GLS extension.
Thanks

**Comment by owebia** [comment]
Hi,
Why did you add https://repo.owebia.com to your composer.json file ?
If you don't need it, remove it (you can do it manually).

If you bought an Owebia module, then you need it and your credentials are visible in your customer account on Owebia Store (page My Downloadable Products).

Best Regards,
A.L.

**Comment by tlf83** [comment]
I bought the module owebia shipping by magento marketplace and I want to use it, I only removed the GLS module of acyba.
Look at my other post about the problem I had with the acyba module.

https://github.com/owebia/magento2-module-advanced-shipping/issues/60

**Comment by owebia** [comment]
The free module Advanced Shipping does not require repo.owebia.com, you can remove the repository from your composer.json.

Best Regards,
A.L.
