### ISSUE TITLE
Access to the store group

### ISSUE THREAD

**Issue by Seb33300** [owebia/magento2-module-advanced-shipping#63]
Hello,

Can you please add the ability to access the store group?

With Magento, we are able to access to the store group with `$store->getGroup()`.

I tried `$store->group` with your module but it seems to not work.
I would like to get the store group code in order to add a condition on a specific store group.

Than you

**Comment by owebia** [comment]
Hi,

You can use `$store->group_id` to get the store group id or `$store->getGroup()` to get the group object (ex: `$store->getGroup()->name`).

Best Regards,
A.L.
