### ISSUE TITLE
Sort order

### ISSUE THREAD

**Issue by gewaechshaus** [owebia/magento2-module-advanced-shipping#64]
Hey @owebia,

sorry for this stupid question, but how can we sort the defined methods?

Tried it like

    'sort_order' 		=> 2,

without success.

Thanks!

Cheers,
Jan

**Comment by owebia** [comment]
Hi,

This is not possible with this extension, Magento does not provide a way to sort shipping methods.

Best Regards,
A.L.

**Comment by gewaechshaus** [comment]
Hi @owebia - ok, many thanks... 

So the default sort order configured in xml is related to shipping carriers only?

If I would extend the shipping method html in a custom template, and would set my attribute called my_sort_order like it is explained in the documentation, it should work or do you see any problems?

```
addMethod('id_038', [
    'title'       => "My Shipping Method",
    'price'       => 10,
]) // No semicolon after closing parenthesis
->set('my_sort_order', 1);

```

Cheers
Jan

**Comment by owebia** [comment]
Hi,

> So the sort order configured in xml is related to shipping carriers only? What is the default sort order? I guess it ain't random...
Magento is sorting by carrier's sort order:  
https://github.com/magento/magento2/blob/2.3.2/app/code/Magento/Quote/Model/Quote/Address.php#L841-L876

> If I would extend the checkout shipping method html in a custom template/ ko observable array, and would set my attribute called my_sort_order like it is explained in the documentation, it should work or do you see any problems?
It should work.

Best Regards,  
A.L.
