### ISSUE TITLE
Unable to edit configuration for new install

### ISSUE THREAD

**Issue by naps1saps** [owebia/magento2-module-advanced-shipping#66]
New installation of Magento 2.3.2
Installing the module, an hour passed and it was not complete.  Cron was drainging resources RAM usage was over 12GB.
Quit cron.
Started cron
Uninstall module
Reinstall module (can't edit configuration)
Uninstall module
Reinstall module (still can't edit configuration)

Page is not loading correctly and clicking on Edit will bounce to the top of the page but does nothing.
![Untitled](https://user-images.githubusercontent.com/5412452/65574118-6e5cc880-df21-11e9-8e1a-159820f9b4d0.png)

**Comment by owebia** [comment]
Hi,

Did you follow every step of installation?

https://github.com/owebia/magento2-module-advanced-shipping#installation

In your case, remove old package, install new one and deploy static content are important steps.

Best Regards,

A.L.

**Comment by naps1saps** [comment]
Apologies for my ignorance.
This is resolved.
