### ISSUE TITLE
composer.json does not allow PHP 7.3

### ISSUE THREAD

**Issue by Yonn-Trimoreau** [owebia/magento2-module-advanced-shipping#68]
Magento 2.3.3 was released yesterday and brings support for PHP 7.3.

Your composer.json should reflect this change

**Comment by Yonn-Trimoreau** [comment]
https://github.com/owebia/magento2-module-advanced-shipping/pull/67

**Comment by owebia** [comment]
Thanks for your PR, fixed in version 2.6.4
