### ISSUE TITLE
Possibility to test a list of SKU ?

### ISSUE THREAD

**Issue by angelflo** [owebia/magento2-module-advanced-shipping#69]
Hi,

Is it possible to test a list of sku and/or Product ID ?
For exemple : I have a list of 10 SKUs (or product_id) , and if one of these SKU is found in the order, I need to hide the mondial relay shipping method : hide('mondialrelay/*')
Do you have a solution to achieve this ?

Thanks a lot

**Comment by owebia** [comment]
Hi,

Are you using Universal Setting Add-on ?

You can use something like this:
```
$condition = false;
foreach ($request->all_items as $item) {
    if (in_array($item->product->sku, [ 123, 456, 789 ])) {
        $condition = true;
        break;
    }
}

if ($condition) {
    hide('mondialrelay/*'); // This will only work in Universal Setting Add-on's configuration
}
```

Best Regards,
A.L.

**Comment by angelflo** [comment]
Hi,

Thanks a LOT for your prompt reply ! :-)

Yes I'm customer of your full Magento 2 package and I have Universal Settings Add-on.

I tried with SKU like this :
if (in_array($item->product->**sku**, [ 'SKU-1', 'SKU-2', 'SKU-3' ])) {
and it seems to work

But for more easy management I tried with product ID :
if (in_array($item->product->**id**, [466,467,485,486,505,1247,1248,1301,1930,1931,2791,2962,3073,3080,3081,3082,3631])) {
and with this it doesn't work ... do you know why ?

**Comment by owebia** [comment]
You should use `$item->product->entity_id`.

Best Regards,
A.L.
