### ISSUE TITLE
GraphQl implementation ?

### ISSUE THREAD

**Issue by angelflo** [owebia/magento2-module-advanced-shipping#71]
Hi,
I would like to know if your owebia shipping extension have graphQl already implemented or if you plan to integrate it in next release ... we'll plan to use PWA to improve speed of website and use this major new feature of magento 2.3

**Comment by owebia** [comment]
Hi,
GraphQL is an alternative to SOAP and REST api's but our module does not provide an api.
Best Regards,
A.L.

**Comment by angelflo** [comment]
Bonjour, 
Tous nos autres fournisseurs d'extension pour Magento2 (Amasty, Mageworx ...) ont publié des mises a jour pour intégrer GraphQl à leur extensions, je pense - et de ce que l'on voit sur tous les forums, je ne suis pas le seul à le penser - que l'évolution de Magento2 en PWA est une avancée majeure et j’espère que vous prendrez en considération ma demande pour ajouter le support GraphQl très rapidement à vos futures mise à jour Owebia pour vos clients ayant acheté la version Pro de votre extension.
Merci d'avance

**Comment by owebia** [comment]
Bonjour,
La documentation de Magento affirme que les méthodes de livraison sont déjà supportées par la plateforme Magento : 

> Support for all product types, payment methods, and shipping methods

https://devdocs.magento.com/guides/v2.3/graphql/index.html

Merci de nous expliquer via notre formulaire de contact ce que vous n'arrivez pas à faire aujourd'hui avec nos extensions en GraphQl.
https://fr.store.owebia.com/contact

Cordialement,
A.L.
