### ISSUE TITLE
Bug avec licence

### ISSUE THREAD

**Issue by angelflo** [owebia/magento2-module-advanced-shipping#73]
Bonjour,
Depuis ce matin j'ai un bug qui est apparu soudainement avec ma licence et l'extension owebia ne fonctionne plus :
Dans le backend magento j'ai un meesage :
Package: Owebia_AdvancedShippingPro 1.1.3

PDOException: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2020-01-24 02:55:50 UTC' for column `com_owebia_license`.`license_v2`.`updated_at` at row 1 in /home/antoine/projects/licy/vendor/php-activerecord/php-activerecord/lib/Connection.php:333 Stack trace: #0 /home/antoine/projects/licy/vendor/php-activerecord/php-activerecord/lib/Connection.php(333): PDOStatement->execute(Array) #1 /home/antoine/projects/licy/vendor/php-activerecord/php-activerecord/lib/Table.php(370): ActiveRecord\Connection->query('UPDATE `license...', Array) #2 /home/antoine/projects/licy/vendor/php-activerecord/php-activerecord/lib/Model.php(887): ActiveRecord\Table->update(Array, Array) #3 /home/antoine/projects/licy/vendor/php-activerecord/php-activerecord/lib/Model.php(799): ActiveRecord\Model->update(true) #4 /home/antoine/projects/licy/src/Licy/Model/LicenseV2.php(81): ActiveRecord\Model->save() #5 /home/antoine/projects/licy/src/Licy/Controller/LicenseController.php(85): Licy\Model\LicenseV2->getStatusData() #6 [internal function]: Licy\Controller\LicenseController->v2Action(Object(Slim\Http\Request), Object(Slim\Http\Response), Array) #7 /home/antoine/projects/licy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array) #8 /home/antoine/projects/licy/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array) #9 /home/antoine/projects/licy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response)) #10 /home/antoine/projects/licy/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response)) #11 /home/antoine/projects/licy/vendor/slim/slim/Slim/App.php(515): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response)) #12 /home/antoine/projects/licy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response)) #13 /home/antoine/projects/licy/vendor/slim/slim/Slim/App.php(406): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response)) #14 /home/antoine/projects/licy/vendor/slim/slim/Slim/App.php(314): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response)) #15 /home/antoine/projects/licy/public/index.php(76): Slim\App->run() #16 {main}

Pouvez-vous me dire en urgence pourquoi je recois soudainement ce message d'erreur alors que tout fonctionnait bien jusqu'à présent et que je n'ai fait aucune modification ni mise a jour de l'extension ???

Merci d'avance de votre réponse rapide !!! très urgent car bloque tout le processus de commande !

**Comment by owebia** [comment]
Bonjour,
Le problème a été corrigé.
Cordialement,
A.L.

**Comment by angelflo** [comment]
franchement votre systeme de licence est une catastrophe ... je n'ai jamais eu aucun pb avec nos multiples autres partenaires payant (amasty, mageworx, xtento ...)
c'est la premiere fois que je vois une extension capable de ruiner un site web lorsqu'elle ne s'authentifie pas ....  ça me semble vraiment incroyable !!!

Nouveau message d'erreur qui apparait maitenant :

Package: Owebia_AdvancedShippingPro 1.1.3

PDOException: SQLSTATE[HY000]: General error: 1364 Field 'is_dev' doesn't have a default value in /home/antoine/projects/licy/vendor/php-activerecord/php-activerecord/lib/Connection.php:333 Stack trace: #0 /home/antoine/projects/licy/vendor/php-activerecord/php-activerecord/lib/Connection.php(333): PDOStatement->execute(Array) #1 /home/antoine/projects/licy/vendor/php-activerecord/php-activerecord/lib/Table.php(359): ActiveRecord\Connection->query('INSERT INTO `li...', Array) #2 /home/antoine/projects/licy/vendor/php-activerecord/php-activerecord/lib/Model.php(844): ActiveRecord\Table->insert(Array) #3 /home/antoine/projects/licy/vendor/php-activerecord/php-activerecord/lib/Model.php(799): ActiveRecord\Model->insert(true) #4 /home/antoine/projects/licy/src/Licy/Controller/LicenseController.php(68): ActiveRecord\Model->save() #5 /home/antoine/projects/licy/src/Licy/Controller/LicenseController.php(84): Licy\Controller\LicenseController->getLicenseV2(Object(stdClass)) #6 [internal function]: Licy\Controller\LicenseController->v2Action(Object(Slim\Http\Request), Object(Slim\Http\Response), Array) #7 /home/antoine/projects/licy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array) #8 /home/antoine/projects/licy/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array) #9 /home/antoine/projects/licy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response)) #10 /home/antoine/projects/licy/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response)) #11 /home/antoine/projects/licy/vendor/slim/slim/Slim/App.php(515): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response)) #12 /home/antoine/projects/licy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response)) #13 /home/antoine/projects/licy/vendor/slim/slim/Slim/App.php(406): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response)) #14 /home/antoine/projects/licy/vendor/slim/slim/Slim/App.php(314): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response)) #15 /home/antoine/projects/licy/public/index.php(76): Slim\App->run() #16 {main}
