### ISSUE TITLE
pb avec test sur attribut et produit configurable

### ISSUE THREAD

**Issue by angelflo** [owebia/magento2-module-advanced-shipping#74]
bonjour,
j'ai un pb avec votre extension sur le test d'un attribut lorsqu'il s'agit d'un produit configurable :
la règle en place est :

addMethod('gls_fr', [
    'title'      => "GLS 48H",
    'enabled'    => _country('FR','MC') && !_postcode('/^20/') && (_count(function ($item) {
                        return $item->product->livraisongratuite == true;
                    }) != $request->package_qty) && ($request->package_value_with_discount < 170),
    'price'      => 6.50
])->set('shipping_icon', 'gls_70.png');

addMethod('gls_offert', [
    'title'      => "GLS 48H - Livraison Offerte",
    **'enabled'    => _country('FR','MC') && !_postcode('/^20/') && ((_count(function ($item) {
                        return $item->product->livraisongratuite == true;
                    }) == $request->package_qty) || ($request->package_value_with_discount >= 170)),**
    'price'      => 0.00
])->set('shipping_icon', 'gls_70.png');

Le but etant d'offrir la livraison lorsque l'attribut 'livraisongratuite' (de type true/false) est sur oui pour tous les produits du panier.
Si on passe la commande depuis un produit simple en livraison gratuite => ca fonctionne correctement : https://www.poussette-marche.com/andersen-bea-chariot-course-treppensteiger-royal-bea-rouge.html

 Si par contre il s'agit d'un produit configurable  : https://www.poussette-marche.com/rolser-chariot-de-courses-6-roues-imax-pliable.html  => cela ne fonctionne pas (alors que le configurable ainsi que tous les produits simple associés ont bien l'attribut livraisongratuite a true

Y'a t'il uns subtilité que je n'ai pas compris ? ou s'agit t'il d'un bug de l'extension ?

merci

**Comment by owebia** [comment]
Bonjour,

Quand un produit configurable est ajouté dans le panier, Magento ajoute en réalité deux produit :
- le produit configurable
- la déclinaison du produit

mais $request->package_qty reste à 1

Si l'attribut a été configuré au niveau global et au niveau des déclinaisons, c'est normal que la fonction _count ne retourne pas la même valeur que $request->package_qty

Dans votre cas, il faut vérifier si le produit est la déclinaison ou le produit configurable (si `$item->parent_item_id` est différent de null, il s'agit d'une déclinaison).

Vous pouvez utiliser la fonctionnalité de debug pour voir quelles sont les valeurs pour vos produits.

Cordialement,
A.L.
