### ISSUE TITLE
Question related to $quote

### ISSUE THREAD

**Issue by gewaechshaus** [owebia/magento2-module-advanced-shipping#75]
Hi,

how is it possible to get the value of a custom quote var?

`$quote->setMyVar('MyValue');`

I already did try $quote->getMyVar() and $quote->my_var without success.

Cheers
Jan

**Comment by owebia** [comment]
Hi,

Have you tried to use the debug to see if your custom variable is populated?
Is your custom variable persistent?
Is it loaded when Magento loads the quote?

Best Regards,
A.L.

**Comment by gewaechshaus** [comment]
@owebia - Hello and many thanks for your instant reply.

I did a quick & dirty test in the cart, which returns correct value, so it seems to be loaded. I will try the same in the checkout.  

`    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $cart = $objectManager->get('\Magento\Checkout\Model\Cart');
    echo $cart->getQuote()->getPackageQty();`

I tried to use the debugger without success, I am not able to receive other informations than the Carrier[owsh1].getConfig which includes the configuration only.

**Comment by gewaechshaus** [comment]
I checked how the debugger works, have to click on it - sorry, my fault.

**Comment by gewaechshaus** [comment]
The $quote object in the debugger does include the value like it should

 'package_qty' => 'DebugQuote'

**Comment by owebia** [comment]
In the module, we get the quote from a quote item to avoid reloading it (see Owebia\AdvancedSettingCore\Model\Wrapper\Quote).
We let Magento load the object for us.

Are you sure your value is persistent?
If yes, you must check why Magento is not loading it in the quote model.

Best Regards,
A.L.

**Comment by gewaechshaus** [comment]
Thanks again! I am actualy testing it, seems to be related to a 3rd party onestepcheckout...

**Comment by owebia** [comment]
If you find out the origin of the problem, please, post your solution here.
And if you like our module, take the time to rank it on Magento marketplace:
https://marketplace.magento.com/owebia-magento2-module-advanced-shipping-setting.html

Have a good day!
