### ISSUE TITLE
Writing any code in this function 

### ISSUE THREAD

**Issue by ducvu91** [owebia/magento2-module-advanced-shipping#76]
i have some function get shipping address to calculate if near by my store, i will delivery in 1 hours. but with your module, i can't code by my ideal. Can i writing anything i want ? Thanks.
![Screenshot_4](https://user-images.githubusercontent.com/19793530/75600820-c4dcbd00-5ae6-11ea-84a3-dcf75f81f9ea.png)

**Comment by owebia** [comment]
Hi,

For security purpose, only some php functions are allowed. Here is the list of functions available:
https://owebia.com/doc/en/magento2-module-advanced-shipping#formulas_functions

Best Regards,
A.L.

**Comment by ducvu91** [comment]
thanks but can i override your module or this function, i need edit a litte code ?

**Comment by owebia** [comment]
Allowed functions are defined here: https://github.com/owebia/magento2-module-advanced-setting-core/blob/master/Helper/Evaluator.php#L45-L87

You can override this Helper like any other Magento class by creating your own module.
Explanation here: https://www.fmeextensions.com/blog/override-magento-2-helper-block-model-and-controller/

**Comment by loppp** [comment]
Just wondering if it is possible to define my variables like the following?

**$base_price1** = 5;

addMethod('method1', [
    'title' => "Standard Shipping",
    'price' => **$base_price1**,
]);

**Comment by owebia** [comment]
Yes you can.

Best Regards,
A.L.
