### ISSUE TITLE
Problème de rafraichissement lorqu'on passe d'une méthode à une autre ?

### ISSUE THREAD

**Issue by Thomas-gt3** [owebia/magento2-module-advanced-shipping#79]
Bonjour,

Sur mon site j'offre les frais de livraison à partir de 59€ d'achat, or dans certains cas l'estimation ne s'actualise pas correctement et donc le client est induit en erreur. Par contre lorsque le client validera le panier pour effectuer la commande, il sera facturé correctement.

Pour mieux focaliser l'origine du problème, j'ai installé une version demo de Magento sans aucun système de cache supplémentaire.

Voici la partie qui pose problème : 
![Screenshot_2020-04-21 Shopping Cart](https://user-images.githubusercontent.com/57117461/79873947-10755e00-83e8-11ea-90e2-303e980c62c7.png)

Voici le code que j'utilise :

addMethod('id_001', [
    'title'      => "Livraison à domicile",
    'enabled'    => $quote->grand_total <= 58.99 && $customer_group->code == "General",
    'price'      => 4.99,
]);

addMethod('id_002', [
    'title'      => "Livraison à domicile",
    'enabled'    => $quote->grand_total >= 59.00 && $customer_group->code == "General",
    'price'      => 0.00,
]);

Je viens de faire une vidéo, à partir d'1m10 on peut voir que le montant reste à 0.00€ alors qu'il devrait revenir à 4.99€ : https://drive.google.com/file/d/1X401El9arv9fnnx_G-vuh60wNHmz_Vtl/view

Avez-vous rencontré le même soucis ? Ou bien est-ce mon code qui n'est pas optimal ?

Merci.

**Comment by owebia** [comment]
Bonjour,

https://owebia.com/doc/en/magento2-module-advanced-shipping#known_issues

Voir la known issue #3

Cordialement,
A.L.

**Comment by Thomas-gt3** [comment]
Pour ne pas me retrouver dans la situation #2 et #3 je viens de remplacer :  

$quote->grand_total
par :
$request->package_value

Le problème persiste, il suffit d'actualiser la page avec F5 pour que la valeur redevienne correcte.
A moins que ça vienne de Magento en lui même, et non du module, actuellement j'utilise Magento 2.3.4 et php 7.2, je vais essayer la branche 2.2 et 2.4 pour voir.

**Comment by owebia** [comment]
Bonjour,
Est-ce que vous avez essayé d'activer le debug pour voir quelle sont les valeurs utilisées pour les calculs à chaque fois ?
Cordialement,
A.L.

**Comment by Thomas-gt3** [comment]
J'ai activé le débogage, je ne suis pas très familiarisé avec ce genre d'outils. Voici le résultat lorsque le bug se présente : 
[Debug.zip](https://github.com/owebia/magento2-module-advanced-shipping/files/4525106/Debug.zip)

**Comment by Thomas-gt3** [comment]
Je viens d'essayer Magento 2.2.10 et le bug est aussi présent.
Par contre sur la version de développement 2.4 il n'y a aucun soucis ! C'est plutôt bon signe.

J'attends la mise à jour Magento 2.3.5 qui devrait arriver la semaine prochaine :
https://devdocs.magento.com/release/

Et on verra bien.

**Comment by owebia** [comment]
Merci pour votre retour.
Si jamais vous trouvez plus d'information (par exemple un ticket Magento qui corrige ce problème), n'hésitez pas à poster ici pour les autres utilisateurs.

Cordialement,
A.L.

**Comment by Thomas-gt3** [comment]
Finalement, j'ai parlé trop vite !
Je viens de réussir à reproduire le bug sur la version de développement 2.4 ainsi que sur la 2.3.5-p1
Le module Owebia n'y est pour rien car en me contentant de configurer Flat Rate et Free Shipping le problème d'affichage persiste et toujours de façon aléatoire.

Ce week-end, je vais créer un post sur la page github de Magento.

**Comment by owebia** [comment]
Bonjour,
Est-ce que vous avez essayé de mettre uniquement le Pays dans la configuration des Champs Requis ?

Cordialement,
A.L.

**Comment by Thomas-gt3** [comment]
Bonjour,

Je viens d'essayer en mettant uniquement le pays :
![Screenshot_2020-05-14 Configuration Settings Stores Magento Admin](https://user-images.githubusercontent.com/57117461/81939114-32808b80-95f6-11ea-8f24-a4c4c405d2ec.png)

Ca ne change rien. Mais à coup sûr ça vient de Magento lui même. J'ai déclaré le problème sur cette page : 
https://github.com/magento/magento2/issues/28145

Pour l'instant il n'y a aucun commentaire.

**Comment by owebia** [comment]
Closing old issue
