### ISSUE TITLE
Magento 2.3.4 error 500

### ISSUE THREAD

**Issue by jaume-solis** [owebia/magento2-module-advanced-shipping#80]
Hi,

I installed this module with composer, all works fine and I could configure it on my one of my stores with a simple config to test it:

addMethod('method1', [
'title' => "Envío con instalación",
'price' => 35,
]);

This is my configuration:

![config_owebia](https://user-images.githubusercontent.com/3274379/81834601-71083e80-9541-11ea-836b-902aedbd323b.JPG)

On frontend I have an exception:

PHP Fatal error:  Uncaught Error: Cannot instantiate interface Owebia\\AdvancedSettingCore\\Model\\CallbackHandlerExtensionInterface in /var/www/clients/client1/web78/web/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121\nStack trace:\n#0 /var/www/clients/client1/web78/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Owebia\\\\Advanced...', Array)\n#1 /var/www/clients/client1/web78/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Owebia\\\\Advanced...')\n#2 /var/www/clients/client1/web78/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Owebia\\\\Advanced...')\n#3 /var/www/clients/client1/web78/web/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Owebia\\\\Advanced...', Array)\n...\n'

Could you help me?

**Comment by owebia** [comment]
Hi,

Did you run `bin/magento setup:di:compile`?

Best Regards,
A.L.

**Comment by jaume-solis** [comment]
Yes I did.

I run this commands:

php composer.phar require owebia/magento2-module-advanced-shipping:^2.5.3
php bin/magento maintenance:enable
php -f bin/magento cache:flush
php -dmemory_limit=2G bin/magento setup:upgrade
php -dmemory_limit=2G bin/magento setup:di:compile
php -dmemory_limit=2G bin/magento setup:static-content:deploy -f --theme Bugmana/default es_ES
php -dmemory_limit=2G bin/magento setup:static-content:deploy -f --theme Magento/backend en_US
php -dmemory_limit=2G bin/magento setup:static-content:deploy -f --theme Magento/backend es_ES
php bin/magento cache:flush
php bin/magento maintenance:disable

**Comment by owebia** [comment]
Can you install the last version (2.8.0) of the module?  
https://github.com/owebia/magento2-module-advanced-shipping#installation

**Comment by jaume-solis** [comment]
Thank you it works!
