### ISSUE TITLE
Missing line number

### ISSUE THREAD

**Issue by Eddcapone** [owebia/magento2-module-advanced-shipping#83]
In the debug window it says `Carrier[owsh1].getConfig - Error - Syntax error, unexpected ',' on line 24` but there are no line numbers in the editor, so I have to count myself. It would be nice if you could add line numbers.

**Comment by owebia** [comment]
Thanks for your feedback.

An advanced editor is available with this addon: https://en.store.owebia.com/magento2-module-adv-ship-functions-addon.html  
You can have line numbers, syntax error detection, etc.

There are no plans to change the functionalities of the default editor.

Best Regards,
A.L.
