### ISSUE TITLE
How it works ? Highest fees

### ISSUE THREAD

**Issue by RobertOttoDE** [owebia/magento2-module-advanced-shipping#85]
Hello, 

I have products (Product A) with Shipping Costs 13€ and 
Products (Product B) with Shipping Costs 80€.

My Problem. 
in Cart Product A = Correct
in Cart Product B = Correct

in Cart Product A + B = 13€

How can i Say give me the highest Shipping Costs from Products in Cart ?

Sorry for my English its not my native Language

**Comment by owebia** [comment]
Hi,

You must use a single `addMethod` call and use `array_sum`.

Here is an example: https://owebia.com/doc/en/magento2-module-advanced-shipping#ex:sum

Best Regards,
