### ISSUE TITLE
Receiving the following issue after install "Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid block type: Owebia\AdvancedShipping\Block\System\Config\Form\Field\About"

### ISSUE THREAD

**Issue by BoutiqueBedCompany** [owebia/magento2-module-advanced-shipping#88]
```
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid block type: Owebia\AdvancedShipping\Block\System\Config\Form\Field\About
Exception #1 (ReflectionException): Class Owebia\AdvancedShipping\Block\System\Config\Form\Field\About does not exist
```

**Comment by owebia** [comment]
Hi,
Have you followed all the instructions given in the [README.md](https://github.com/owebia/magento2-module-advanced-shipping#installation) file?

The class exists https://github.com/owebia/magento2-module-advanced-shipping/blob/master/Block/System/Config/Form/Field/About.php
You may probably have an issue with the installation.

Can you confirm which packages and versions you have installed using composer?

Best Regards,
A.L.

**Comment by BoutiqueBedCompany** [comment]
Hi,
thanks for your quick reply. 
Is the extension compatible with Magento version 2.3.5-p2?

When I run composer require owebia/magento2....et.c. I also receive this error message 
"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - owebia/magento2-module-shared-php-config 3.0.3 requires magento/framework ^100.0|^101.0|^102.0|^103.0 -> no matching package found.
    - owebia/magento2-module-advanced-shipping 2.8.8 requires owebia/magento2-module-shared-php-config ^3.0.3 -> satisfiable by owebia/magento2-module-shared-php-config[3.0.3].
    - Installation request for owebia/magento2-module-advanced-shipping ^2.8.8 -> satisfiable by owebia/magento2-module-advanced-shipping[2.8.8].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content."

**Comment by owebia** [comment]
Yes, the module is compatible with Magento 2.3.5-p2.

Magento 2.3.5-p2 requires magento/framework:102.0.5-p2 so this should not conflict with the version required by Advanced Shipping module.

Can you post the full command used and the full output of this command please?

Best Regards,
A.L.

**Comment by BoutiqueBedCompany** [comment]
![Screenshot (50)](https://user-images.githubusercontent.com/74540374/99261374-8e7dd400-2814-11eb-900f-bc87d37f319b.png)

**Comment by owebia** [comment]
It seems you are using an outdated version of composer. Maybe the `-p2` in the version number is not well handled by your version. Can you try to update composer and try again?

Can you also check the exact version of magento/framework installed on your instance please?

**Comment by BoutiqueBedCompany** [comment]
I have updated the composer but I am still receiving the same message.
![Screenshot (55)](https://user-images.githubusercontent.com/74540374/99271858-03560b80-281f-11eb-9c99-06f6da91a138.png)

**Comment by owebia** [comment]
Are you running the command in Magento root?

**Comment by BoutiqueBedCompany** [comment]
Yes I am

**Comment by owebia** [comment]
What does this command return? `composer show magento/framework`

**Comment by BoutiqueBedCompany** [comment]
[InvalidArgumentException]
  Package magento/framework not found

**Comment by owebia** [comment]
It really seems you are not executing commands from magento root folder

**Comment by owebia** [comment]
@BoutiqueBedCompany did you manage to install the module?

**Comment by BoutiqueBedCompany** [comment]
Hi, no I didn't. I installed WebShopApps Matrix Rates shipping instead and that works fine for me.

**Comment by owebia** [comment]
Thanks for your response.
Have a good day.
A.L.
