### ISSUE TITLE
Magento 2.4.1

### ISSUE THREAD

**Issue by gkueny** [owebia/magento2-module-advanced-shipping#89]
Hello,

I couldn't find any information about the compatibility of this module.

Is it compatible/tested with the latest Magento 2.4.1 version?
And if not, do you think there is a reason why it might not be?

**Comment by owebia** [comment]
Hi,

Yes, Magento 2.4 is supported.
You should be able to use it on Magento 2.4.1.

Best Regards,
A.L.
