### ISSUE TITLE
Change title of Owebia module for one method

### ISSUE THREAD

**Issue by marcinex** [owebia/magento2-module-advanced-shipping#90]
Hi Owebia!
I have another small issue I can't resolve. I have around 20 different methods with correspondings names, everything works well (love it) but for one of them I would like to change name in frontend (but not title of method). Please, take a look for picture:
![image](https://user-images.githubusercontent.com/3911452/101748274-a3c0e800-3acc-11eb-9107-8387a100fed8.png)

The names from shipping methods are "Przesyłka przedpłacona" and "Przesyłka za pobraniem" which are ok but I would like to change this "Kurier" name for second method to "Poczta". I set "Kurier" as a name of Your Owebia Shipping. Can I change it somehow in easy way only for this one?

Regards
Marcin

**Comment by owebia** [comment]
Hi,
The frontend displays the title of the method and the carrier's title.
The carrier's title is unique to a carrier, you can't change it for one method only.

If you need to separate methods in different carriers, you can do it with our Unlimited Carriers Plugin:
https://en.store.owebia.com/magento2-module-adv-ship-unlimited-carriers-addon.html

If you need to share conditions between different carriers, you can use our Universal Setting Plugin:
https://en.store.owebia.com/magento2-module-adv-ship-universal-setting-addon.html

Both are included in Advanced Shipping Pro:
https://en.store.owebia.com/magento2-module-advanced-shipping-pro.html

Best Regards,
A.L.
