### ISSUE TITLE
Internal Server Error (500) estimate-shipping-methods

### ISSUE THREAD

**Issue by Mo3ta9em93** [owebia/magento2-module-advanced-shipping#91]
Hello,
Thank you for this wonderful extension
I was using this extension with no issues then suddenly I've been getting this error on checkout:
` main.CRITICAL: Report ID: webapi-60187699849de; Message: Class string[] does not exist {"exception":"[object] (Exception(code: -1): Report ID: webapi-60187699849de; Message: Class string[] does not exist at /html/vendor/magento/framework/Webapi/ErrorProcessor.php:208, ReflectionException(code: -1): Class string[] does not exist at /html/vendor/magento/framework/Reflection/MethodsMap.php:159)"} []`
enviroment:
Magento 2.3.5
Owebia advanced shipping 2.8.8
All other shipping methods are working

Thank you

**Comment by owebia** [comment]
Hi,

Are you using an extension that override the class `\Magento\Framework\DataObject`?

This can cause an issue with this code:
https://github.com/owebia/magento2-module-advanced-shipping/blob/master/Plugin/Magento/Framework/Reflection/DataObjectProcessor.php

Best Regards,
A.L.

**Comment by Mo3ta9em93** [comment]
Yes, it was caused by a recent extension.
Thank you
Best Regards,
