### ISSUE TITLE
Owebia debug not working

### ISSUE THREAD

**Issue by laura5101** [owebia/magento2-module-advanced-shipping#92]
Hi there,

I'm trying to debug some shipping methods on Magento's Owebia shipping module. I'm trying to do this via the admin panel as I don't have server access. 

![image](https://user-images.githubusercontent.com/73903823/110660480-84b11f80-81bb-11eb-966a-db4c32195169.png)

When I try to click on the debug option in the Owebia module I get a server error

![image](https://user-images.githubusercontent.com/73903823/110660389-6ea35f00-81bb-11eb-8b93-08dda293b39d.png)

It worked fine last week and I haven't changed anything since (I don't think?!) - any ideas on what the problem might be?

Many thanks!!

Laura

**Comment by owebia** [comment]
Hi,
The debug create a huge file if you let the option enabled.
The file is probably too big to be handled.
You can delete the file located in var/log/

Best Regards,
A.L.

**Comment by laura5101** [comment]
Argh - ok thank you!

Does deleting the file in var/log require developer access, or can I do it from the admin panel?

If it requires developer access, can you possibly let me know _exactly_ what it is I need to ask for so that the developer can't possibly make a mistake?

Thank you!

Laura

**Comment by owebia** [comment]
The file to remove is `var/log/owebia_advancedsettingcore.log`
You need file access to remove it as it cannot be done from the backend.

**Comment by laura5101** [comment]
Many thanks for your very prompt reply!!!
I might post a separate ticket about the shipping issue itself, as you might have a better way of solving it than my hack!!!
Many thanks
Laura
