### ISSUE TITLE
Get the textual value for the 'Admin' store of an attribute of type select

### ISSUE THREAD

**Issue by rlienhar** [owebia/magento2-module-advanced-shipping#94]
Hi,
in a new Magento 2 store an attribute 'Shipping_Type' was defined to select the shipping costs for every product. With the command

'addMethod('id_013', [
    'title' => "Standard shipping",
    'enabled' => $request->dest_country_id == 'DE'
					&& count(
                           array_filter($request->all_items, function ($item) {
                            return $item->product->getAttributeText('Shipping_Type') == 'Standard shipping, this item will be shipped securely packed in DHL standard shipping.'
                        })
                    ) > 0,
    'price' => 5.90,
]);'

I can read the description for this attribute. I can't find the selected attribute itself.
Is there a solution for reading out the self-defined attributes?

**Comment by owebia** [comment]
Hi,

Sorry, I don't fully understand.  
What are you calling a self-defined attribute?
What are you calling the description of an attribute? Is is the textual value for a "select" type attribute?
What do you mean by "selected attribute itself"? Is is the ID of the value for a "select" type attribute?

Best Regards,
A.L.

**Comment by rlienhar** [comment]
Sorry for the incomplete and inaccurate description. 
It is a custom attribute that I created in Magento in addition to Magento standard attribute. 
I am looking for a way to query the status of the custom created attribute label.
With the description of an attribute is meant the values of the attributes.
Example:
Attribute Label: Shipping_Type
Values of the attributes: Standard shipping or Cool shipping
With ->getAttributeText('Shipping_Type' I get the description of the attribute, not the value itself.

Best Regards
rlienhar

**Comment by owebia** [comment]
Can you post a screenshot of how the attribute's values are defined and give a concrete example of what you get with `getAttributeText('Shipping_Type')` and what you would like to get instead?

**Comment by rlienhar** [comment]
I want the red marked items to select the price, with ->getAttributeText('Shipping_Type') I get the yello marked description.

<img width="1051" alt="Attribute Properties" src="https://user-images.githubusercontent.com/28999830/111168137-0e893000-85a2-11eb-9a14-7e17c451aef1.PNG">
<img width="520" alt="Shipping-Attribute Label" src="https://user-images.githubusercontent.com/28999830/111168157-134de400-85a2-11eb-8a78-1574ff9f32d5.PNG">

**Comment by owebia** [comment]
What you call "the description" is the value in the "Deutsch" store.
What you call "the value" is the value in the "Admin" store.
`getAttributeText` gets the value in the current store, in your case the "Deutsch" one.

You can use the attribute's numeric value instead of using the textual value. This will always be the same no matter the store.

If several users ask for this functionality (getting the Admin textual value of a select attribute), we may add it later in a new release.

Best Regards,
A.L.

**Comment by rlienhar** [comment]
Thanks for your feedback and clarification.
I'm looking for the cmd to get the attribute's numeric value. 
Perhaps you can give me a hint.

It would be great to add the functionality to get the Admin textual value.
Best Regards
rlienhar

**Comment by owebia** [comment]
You can get the numerical value like this: `$item->product->Shipping_Type`

Best Regards,
A.L.

**Comment by rlienhar** [comment]
It works with the value!! Thanks for feedback.
I'm a little bit astonished, I recieved values like 3 or 4  depends of the selected shipping criteria.
It's possible to list all values, from 0 to 4 in an array?

Thanks and best regards
rlienhar
