### ISSUE TITLE
Client de votre extension payante, NE FONCTIONNE PLUS !

### ISSUE THREAD

**Issue by angelflo** [owebia/magento2-module-advanced-shipping#95]
Bonjour,

Notre site est down car votre extension semble ne plus fonctionner :

The "https://repo.owebia.com/packages.json" file could not be downloaded: failed to open stream: Connection refused
https://repo.owebia.com could not be fully loaded, package information was loaded from the local cache and may be out of date

D'autre part votre site internet owebia.com semble etre down lui aussi !

Pouvez-vous confirmer que vous avez un probleme de votre coté ?
Et si tel est le cas, pouvez-vous également vous assurer que votre système de vérification des licences ne soit PAS tributaire d'une liaison à votre site car cela signifie que tous vos clients perdent l'acces à l'extension lorsque vous etes down .... ce qui est totalement inacceptable.

Merci d’avance.

**Comment by owebia** [comment]
Bonjour,

Une opération de maintenance sur notre serveur est en cours suite à un problème de mise à jour.

Cordialement,
A.L.

**Comment by angelflo** [comment]
Bonjour,

Pouvez-vous faire le nécessaire pour que votre extension ne cesse pas de
fonctionner dans de pareil cas de figure !!

Merci

**Comment by owebia** [comment]
Si le repo est down, le package n'est pas disponible mais cela n'empêche pas l'extension de fonctionner

**Comment by paugnu** [comment]
Bonjour,

Nous avons le même problème. Ce n'est pas la première fois que l'extension arrête de fonctionner à cause de cette histoire de licence. C'est vraiment bloquant car nos clients ne peuvent plus faire de commandes. 

Cela ne fonctionne pas encore pour nous:

![image](https://user-images.githubusercontent.com/506393/111613490-dd497380-87de-11eb-9d75-a7346e46a817.png)

**Comment by owebia** [comment]
Nous procédons au plus vite pour rétablir le service et nous allons réfléchir à une solution pour les licences.  
Il me semblaient que la vérification des licences n'empêchait pas les modules de fonctionner (même si l'erreur est affichée sur la page des licences).

Si vous avez des éléments de logs qui donnent des infos supplémentaires sur ce qui bloque, je suis preneur.

Cordialement,
A.L.

**Comment by owebia** [comment]
Est-ce que vous avez temporairement la possibilité de désactiver la vérification de licence dans le fichier indiqué en attendant que le service soit rétabli ?

**Comment by paugnu** [comment]
J'ai la possibilité de changer le code, oui. Qu'est-ce que je dois faire exactement ?

**Comment by owebia** [comment]
Dans le constructeur du fichier `vendor/owebia/magento2-module-adv-ship-functions-addon/Model/CallbackHandler.php`, vous pouvez remplacer
`if (!$this->license->isValid()) {`
par
`if (false && !$this->license->isValid()) {`

**Comment by paugnu** [comment]
Merci beaucoup, avec ce changement ça marche. Je vois toujours le problème de licence dans le backoffice, mais dans le frontend je vois les méthodes d'envoi correctement. 

Peut-être les licences devraient fonctionner de la forme suivante :
- Licence nécessaire pour toute la conf du BO 
- Mais pour le frontend, cela devrait fonctionner dans tous les cas

Au moins avec ce fonctionnement, si le serveur ne fonctionne plus, les méthodes sont toujours disponibles dans le frontend.

**Comment by owebia** [comment]
Merci pour votre retour.
Nous allons effectuer des modifications sur la vérification de licence pour notre prochaine release.

Nos services ont été rétablis. Pouvez-vous me confirmer que c'est bon de votre coté ?

Cordialement,
A.L.

**Comment by paugnu** [comment]
Merci, ça marche à nouveau :)

**Comment by owebia** [comment]
Merci pour votre patience.
Encore désolé pour l'indisponibilité de nos services.

Cordialement,
A.L.

**Comment by owebia** [comment]
Malheureusement, le serveur est à nouveau down, toujours lié à notre problème de mise à jour.
Nous essayons de rétablir le service au plus vite
