### ISSUE TITLE
Error when trying to upgrade

### ISSUE THREAD

**Issue by SteelDragoncc** [owebia/magento2-module-advanced-shipping#98]
How can I fix this?
Running on magento 2.3.7 but i cant update to 2.4.2 as long as this one is not upgrading.

composer require owebia/magento2-module-advanced-shipping:^2.8.9
./composer.json has been updated
Running composer update owebia/magento2-module-advanced-shipping
Loading composer repositories with package information                                                       In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - owebia/magento2-module-advanced-setting-core is locked to version 2.8.0 and an update of this package was not requested.
    - owebia/magento2-module-advanced-setting-core 2.8.0 requires php ~5.5.0|~5.6.0|~7.0.0|~7.1.0|~7.2.0|~7.3.0 -> your php version (7.4.16) does not satisfy that requirement.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by owebia** [comment]
Hi,

`owebia/magento2-module-advanced-setting-core` is an obsolete dependency of Advanced Shipping.

## Case 1: direct dependency

You added `owebia/magento2-module-advanced-setting-core` as a direct dependency.  
This shouldn't have been done unless your intention was to lock to a specific version.

Solution: simply remove the direct dependency.

## Case 2: dependency via a module

You should remove any obsolete module requiring this obsolete dependency (e.g. `owebia/magento2-module-advanced-shipping-setting`, see [installation instructions](https://github.com/owebia/magento2-module-advanced-shipping#installation)).

Best Regards,
A.L.
